CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    content TEXT,
    modified TEXT NOT NULL,
    folder_id INTEGER REFERENCES noteful_folders(folder_id) NOT NULL
)